### ISSUE TITLE
MarsTable errors

### ISSUE THREAD

**Issue by NadiaHuisjes** [duderstadt-lab/mars-core#14]
Hi Karl,

Thomas pointed out the following error:
When you generate a MarsTable using the first script of this tutorial (https://duderstadt-lab.github.io/mars-docs/tutorials/scripting/marstable/) you get the table as you would expect. However, if subsequently script 2 is ran, the script yields no result.

I tested this a bit and I observe the same behaviour. I also have this error when I use both scripts the other way around (first run script 2, then script 1). 

Next to this, when I close a generated table, then run a script again, no window with the table pops up. 

Both errors were resolved by closing the Fiji application, and restarting it again. But emerged again when performing the same actions again as written above.

Could you please take a look?

Nadia

**Comment by NadiaHuisjes** [comment]
Just a comment, the error that I do not get a new table window after I close it also occurs when trying to create a TableDisplay. So I would say this is a Fiji related issue.

'''
#@output org.scijava.table.DefaultDoubleTable table
import org.scijava.table.*
table = new DefaultDoubleTable()
DoubleColumn col = new DoubleColumn("Nums")
col.add(3.123d)
col.add(34.12d)
col.add(1.309d)
table.add(col)
'''

**Comment by karlduderstadt** [comment]
Thanks for reporting this issue. I have reproduced it. 

By default Fiji / Scijava will not allow you to display two tables that contain all the same values. When the second one is created and display is never created. I will have to look around more to see exactly where the code is that controls this within scijava, but it seems that the values of tables are compared and the display is never created if two tables will have the same values. This is also the case for MarsTables. However, there might be a way to override this. So... Your first comment makes sense and has not yet been fixed.

The commit above fixes your second comment. Now if you create a table and then close it, you can create it again. It seems the display was not removed when the window is closed. That is now fixed.

I am not entirely sure what to do about the second issue. So if you run the same script several times you would expect a table to open each time?

At least within the MarsTableService that keeps track of tables on our side, all tables must have a unique name. The script doesn't give a name at all currently, so we could add that. 

I guess an error message would be helpful if the table is already open and you run the script a second time...

**Comment by karlduderstadt** [comment]
Awww found it - https://github.com/scijava/scijava-table/blob/5f8eaf2b0daba17fd0cc1ad6caef50af9232dd25/src/main/java/org/scijava/table/DefaultTableDisplay.java#L76-L89

**Comment by karlduderstadt** [comment]
duderstadt-lab/mars-fx@917c298 resolves this issue. Actually, I was wrong about the MarsTableService. So I converted it a while back to just be a wrapper for the scijava object service. So it will also ask the ObjectService for a list of MarsTable and the names can all be the same. 

Ultimately, you shouldn't make several tables that are the same with the same name. That is not useful and you will always retrieve the first one you created with that name in dialogs... So that would add a lot of confusion. But now you can create as many as you like and they should all open. Now as well they should be properly disposed of on closing the windows and will not sit around in the background, which could certainly cause further confusion later...

This will come with the next release of mars-fx or you can get a snapshot if you like. Just let me know.
