### ISSUE TITLE
Deleting molecules from Archive throws IndexOutOfBoundsException

### ISSUE THREAD

**Issue by mjosch** [duderstadt-lab/mars-core#3]
Hi,

I encountered an error when trying to delete molecule entries from a MoleculeArchive. The exception raises independent of using tags.

<img width="606" alt="DeleteMolecules" src="https://user-images.githubusercontent.com/39280948/79866074-7d82f680-83dc-11ea-8f80-9fcd87d2a10d.png">
<img width="748" alt="DeleteMolecules_Exception" src="https://user-images.githubusercontent.com/39280948/79866078-7f4cba00-83dc-11ea-8dda-59342afc8a41.png">

**Comment by karlduderstadt** [comment]
Hi mjosch,

Thanks for reporting this issue. This is a problem in mars-fx. The gui attempts to keeps track of the currently selected UID and restore that record after the tagged molecules are deleted. Unfortunately, depending on the number of records deleted this is unstable. I have implemented a different approach, which hopefully fixes the problem.

I am going to close your issue here and create one on the mars-fx site, then push the updated version there
