### ISSUE TITLE
Segment Distribution Builder 

### ISSUE THREAD

**Issue by NadiaHuisjes** [duderstadt-lab/mars-core#7]
Hi Karl,
Like we discussed in the meeting, we want to change the segment distribution builder tool in the following way:
- Remove the 'duration' and 'processivity' options
- Improve the parameter naming (xmin, xmax)

Eventually the tool can be discontinued and integrated in the widgets environment.

**Comment by karlduderstadt** [comment]
Hi @NadiaHuisjes,

I went ahead and removed the SegmentDistributionBuilder because it is not being used and I think it is better if these plots are main in jupyter notebooks or using the dashboard chart widgets. I left a SegmentDistributionBuilder class that is in the kcp package. This could be used in scripts to build distributions.

The Builder was removed in commit a093d1f. I am going to go ahead and close this issue.
